config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/sort', to: 'posts#sort'

  resources :posts do
    member do
      post 'vote'
    end

  	resources :comments do
      member do
        post 'vote'
      end

    end

  end

  resources :categories
  resources :users
    
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_categories
	has_many :posts, through: :post_categories
	validates :name, presence: true


  include Sluggable_Loc

  sluggable_column :name
   
   


	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	include Voteable_Loc5
	belongs_to :user
	belongs_to :post
	validates :body, presence: true  
   
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :post_categories
	has_many :categories, through: :post_categories
  	
	validates :url, presence: true
 	
  include Voteable_Loc5
	include Sluggable_Loc

  sluggable_column :title


     

    
   
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	include Sluggable_Loc
	has_many :posts
	has_many :comments
  has_many  :votes
 	has_secure_password validations: false

  validates :username, presence: true, uniqueness: true       
  validates :password, presence: true, on: :create, length: {minimum: 5}     
         
  sluggable_column :username

     
  def admin?
    self.role == 'admin'
  end

  def moderator?
    self.role == 'moderator?'
  end
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :voteable, polymorphic: true

    validates_uniqueness_of :user, scope: [:voteable_id, :voteable_type]
end

	

app/controllers/application_controller.rb
require 'will_paginate/array'
class ApplicationController < ActionController::Base
   require 'will_paginate/array'
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  def logged_in?
    !!current_user
  end
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end;
  def require_user
    if !logged_in?
      flash[:error] = "Must be logged in to do that."
      redirect_to root_path
    end
  end

   def require_admin
    access_denied unless logged_in? and current_user.admin?
  end

  def access_denied
    flash[:error] = "You can't do that."
    redirect_to root_path
  end

  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
   
def index
  @categories = Category.all

end

def create
  @category = Category.new(category_params)
  if @category.save
     redirect_to categories_path
  else
      render "new"
  end

end


def edit
    @category = Category.find_by slug: params[:id]
end

def show
    @category = Category.find_by slug: params[:id]
 
    case params[:sort]
       
        when "newest"
         @categories = @category.posts.order('created_at DESC').all       
	else
           @categories = @category.posts     
        end       
      respond_to do |format|
            format.html do
              @categories

            end
               format.js

          end
end

def new
    @category = Category.new

end
def update
     @category = Category.find_by slug: params[:id]
   if @category.update(category_params)
	flash[:notice] = "This post is updated "
	redirect_to category_path(@category)
   else
	render "edit"
   end

end	

private
 def category_params
    params.require(:category).permit(:name)

 end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :require_user

  def create
    @post = Post.find_by slug: params[:post_id]
    @comment = @post.comments.build(params.require(:comment).permit(:body,:user_id))
    @comment.user = current_user   

    if @comment.save
      flash[:notice] = "Your comment was added "
	    redirect_to post_path(@post)
    else
      render 'post/show'    
    end
    
  end 
    	
  def vote
    @comment = Comment.find(params[:id])     
    @vote = Vote.create(voteable: @comment, user: current_user, vote: params[:vote])
      respond_to do |format|
        format.html do
          if @vote.valid?
            flash[:notice] = 'Your vote was counted.'
          else
            flash[:error] = 'You can only vote on a post once.'
          end

          redirect_to :back
      end
      format.js
      end
  end
end
   

app/controllers/posts_controller.rb
require 'will_paginate/array'
class PostsController < ApplicationController

	before_action :set_post , only: [:edit,:show,:update]
	before_action :require_user, except: [:show, :index] 
		 
	def index
		
	  	case params[:sort]
				when "hottest"
					@posts = Post.all.sort_by{|post| -post.comments.size}.paginate(:page => params[:page], :per_page => 10)
				when "oldest"
					@posts = Post.order('created_at ASC').paginate(:page => params[:page], :per_page => 10)       
				else        
					@posts = Post.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)           
			end      
									 
				respond_to do |format|
					format.html do

					end	
							
					format.js 

      	end
  end

	def show
	 @comment= Comment.new
	end  
	
	def create
		@post = Post.new(post_params)
		@post.user = current_user
		if @post.save
			flash[:notice] = "Your post was created."
			redirect_to posts_path
		else
			render :new
		end
	end
			
	def vote   
		@post = Post.find_by slug: params[:id]         
		@vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])

		respond_to do |format|
			format.html do
				if @vote.valid?
					flash[:notice] = 'Your vote was counted'
				else
					flash[:error] = "You can onlu vote on a post once"
				end
					redirect_to :back     
			end
				format.js    
		end 

	end
		
	def edit;end
	
	def new
		@post = Post.new
	end
	
	def set_post     
		@post = Post.find_by slug: params[:id]
	end

	def update
		if @post.update(post_params)
			flash[:notice] = "This post is updated "
		  redirect_to post_path(@post)
		else
			render :edit
		end
	end
 
	private
		def post_params
			params.require(:post).permit(:title, :url, :description, category_ids: [])
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'new'
  end

  def create
    user = User.where(username: params[:username]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you've logged in."

      redirect_to root_path
    else
      flash[:error] = "There is something wrong with your username or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]
  def index

  end
  def show

  end 

  def new
    @user = User.new
    
    render "new"
  end
 
  def create
    @user = User.new(users_params) 

    if @user.save
	    flash[:notice] = "You are registered"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end

  end
 
  def edit
 
  end  
 
  def set_user
    @user = User.find_by slug:params[:id]
  end  
  
  def update
   
    if @user.update(users_params)
	    flash[:notice] = "This post is updated "
		  redirect_to user_path(@user)
		else
			render :edit
		end
	end
 
  def users_params
    params.require(:user).permit(:username,:password,:time_zone)
  end
 
   def require_same_user
    if current_user != @user
      flash[:error] = "You're not allowed to do that."
      redirect_to root_path
    end
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
   def fix_url(str)
      str.starts_with?("http://") ? str :"http://#{str}"
   end
   def display_datetime(dt)
      dt.strftime('%m%d%Y %l:%M%P %Z')

   end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/edit.html.erb
<%= form_for @category do |x| %>
	<%= x.label :name %>
	<%= x.text_field :name %>
	<%= x.submit "Update the category" %>
<% end %>

app/views/categories/index.html.erb
<h2>List of all Categories: </h2>

<% @categories.each do |x| %>
	<h4>Category name:<%= x.name %> </h4>
	<%= link_to("Edit the Category",edit_category_path(x)) %>
	<br>
<% end %>

app/views/categories/new.html.erb
<%= render "partials/errors", obj: @category %>
<p style='color:red'>
<h2>New Cateogry:</h2>
<%= form_for @category do |x| %>
	<%= x.label :name %>
	<%= x.text_field :name %>
  <br>
  <%= x.submit "Create a new category" %>
<% end %>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>
<%= render 'shared/content_title', title: header  %>
<div class = "posts">

<% @categories.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

</div>

app/views/categories/show.js.erb
$('.post').remove();

<% @categories.each do |post| %>
  $('.posts').append('<%= j render "posts/post", post: post %>');
<% end %>

app/views/comments/_comment.html.erb
<br/><b><%= comment.post.title %></b>
<br/>
<%= comment.body %>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes%> votes")  
<% else %>
  alert('You can only vote on a comment once.');
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>

<div class='nav_item'>
  <%= link_to "Hottest", posts_path(:sort => 'hottest'),class: 'btn btn-small' %>
  
</div>

<div class='btn-group nav_item'>
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Sorted by <span class='caret'></span>
  <% end %>
  <ul class='dropdown-menu'>   
    <li>
      <%= link_to "Newest", request.parameters.merge({:sort => "newest"}),method: "get", remote: true %>
      <%= link_to "Oldest",  request.parameters.merge({:sort => "oldest"}),method: "get", remote: true %>
    </li>
  </ul>
</div>

<div class='btn-group nav_item'>
  <%= link_to 'Newest Posts', posts_path, sort:"newest" %>
</div>

<div class='btn-group nav_item'>
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class='caret'></span>
  <% end %>
  <ul class='dropdown-menu'>
    <% Category.all.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category)%>
      </li>
    <% end %>
    <% if logged_in? and current_user.admin? %>
      <li class='divider'></li>

      <li>
        <%= link_to(new_category_path) do %>
          <i class="icon-plus"></i>
            New Category
        <% end %>

	      <%= link_to(categories_path) do %>
          <i class="icon-plus"></i>
          Edit Category
        <% end %>

      </li>
    <% end %>
  </ul>
</div>

<% if logged_in? %>
  <div class='nav_item'>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
  </div>
  <div class='btn-group nav_item'>
    <%= link_to('', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown') do %>
      <%= current_user.username %>
      <span class='caret'></span>
    <% end %>
    <ul class='dropdown-menu'>
      <li>
        <%= link_to edit_user_path(current_user) do %>
          <i class='icon-pencil'></i>
          edit profile
        <% end %>
      </li>
      <li>
        <%= link_to user_path(current_user) do %>
          <i class='icon-user'></i>
          view profile
        <% end %>
      </li>
      <li>
        <%= link_to logout_path do %>
          <i class='icon-circle-arrow-left'></i>
          logout
        <% end %>
      </li>
    </ul>
  </div>
<% else # logged out%>
  <div class='nav_item'>
    <%= link_to 'Register', register_path, class: 'btn btn-success btn-small' %>
  </div>
  <div class='nav_item'>
    <%= link_to 'Log in', login_path, class: 'btn btn-small' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/partials/_contentTitle.html.erb
<%= title %>

app/views/partials/_errors.html.erb
<% if obj.errors.any? %>
	<h5>Please fix the following messages </h5>
	
	<% obj.errors.full_messages.each do |x| %>
		<ul>
			<li><%= x %></li>
		</ul>
	<% end %>

<% end %>

app/views/partials/_form.html.erb
<h4>Rails model backed form helpers</h4>

<%= form_for  @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :url %>
	<%= f.text_field :url %>
	<br>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<br>

	<div class = 'control-group'>
	  <%= f.label "Categories" %>
	  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
	  <% cb.label(class:"checkbox inline"){cb.check_box(class: "checkbox") + cb.text} %>
	  <% end %>
	</div>

	<%= f.submit(@post.new_record? ? "Create a Post": "Update the post" ) %>
	
<% end %>

 
        

app/views/posts/_post.html.erb
<div class = "post">
  <div class="row">
    <% if current_user %>
    
      <div class='span0 well text-center'>
        <%= link_to vote_post_path(post, vote: true), method: "post", remote: true do %>
          <i class='icon-arrow-up'></i>
        <% end %>

        <br/>
        <span id = "post_<%= post.slug %>_vote"><%= post.total_votes %></span>
        <br/>
      
        <%= link_to vote_post_path(post, vote: false), method: "post", remote: true do %>
          <i class='icon-arrow-down'></i>
        <% end %>

      </div>

    <% end %> 

    <div class='span8 well'>

      <% post.categories.each do |category| %>
        <span style = "background:dimgray;border-radius:35px;padding:4px"><%= link_to category.name, category_path(category) %></span>
      <% end %> 

      <h4><%= link_to post.title, fix_url(post.url) %></h4>
      <p><%= post.description %> </p>
      <p>
        <span class='quiet'>posted by</span> <%= link_to post.user.username, user_path(post.user) %>
        <small>at <%= display_datetime(post.created_at) %></small>
      </p>
      <small>
      <span>
        <%= link_to("#{post.reload.comments.size} comments", post_path(post)) %>
      </span>
      </small>
         
      <% if post.user == current_user %>
       <span class="edit"><%= link_to "Edit", edit_post_path(post) %></span>
      <% end %>

    </div>

  </div>

</div>

app/views/posts/edit.html.erb
<%= render "partials/form" %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<div class="posts">
	<% @posts.each do |post| %>
	  <%= render 'post', post: post %>
	<% end %>
</div>

<%= will_paginate @posts %>

app/views/posts/index.js.erb
$('.post').remove();

<% @posts.each do |post|  %>
  $('.posts').append('<%= j render "post", post: post %>');
<% end %>

app/views/posts/new.html.erb
<%= render "partials/errors", obj: @post %>
<%= render "partials/form" %>

app/views/posts/show.html.erb
<b><p>Title:</p></b><%= @post.title %>
<b><p>Url:<p></b><%= link_to @post.url,fix_url(@post.url) %>
<b><p>Description:</p></b><%= @post.description %>
<p>Created at:</p><%= display_datetime(@post.created_at) %>
<br>
<b><p>Comments :</p></b>

<% @post.reload.comments.each_with_index do |x,index| %>
  <div class="row">

    <div class='span0 well text-center'>

      <%= link_to vote_post_comment_path(x.post,x, vote: true), method: "post", remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>

      <br/>

      <span id='comment_<%= x.id %>_votes'><%= x.total_votes %></span>

      <br/>
      
      <%= link_to vote_post_comment_path(x.post,x, vote: false), method: "post", remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>

    </div> &nbsp &nbsp <%= x.body %>" by <%= link_to x.user.username,user_path(x.reload.user) %>

  </div>

  </br>

<% end %>

<% if logged_in? %>   
  <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :body %>
    <%= f.hidden_field :username, :value => current_user.username %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <br>
    <%= f.submit "Create Comment" %>
  <% end %>

  <br/>
  
<% else %>
  <form action = '/login'>
    <input type = 'submit'  value= "Create Comment" />
  </form>
<% end %>

<div>
  <%= form_for @post do |f| %>
    <%= f.label "Categories" %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class:"checkbox inline"){cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
 <% end %> 
 
</div>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
	$('#post_<%= @post.slug %>_vote').html("<%= @post.total_votes %> votes")

<% else %>
	alert("You already votes on that")
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr/>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
    <div class='alert alert-error span8' >
      <h5> There were some errors: </h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class='well'>
  <%= form_for @user do |f| %>
  <%= render 'shared/errors', obj: @user %>
    <div class='control-group'>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: 'btn btn-success' %>
    <% end %>
</div>    

app/views/users/edit.html.erb
<div class='well'>
  <%= form_for @user do |f| %>
  <%= render 'shared/errors', obj: @user %>
    <div class='control-group'>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class='control-group'>
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %>
    </div>
    <%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: 'btn btn-success' %>
  <% end %>
</div>

app/views/users/new.html.erb
<h2>Users Register: </h2>
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<div class='well'>
  <dl class='dl-horizontal'>
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
    
  </dl>
</div>

<h5><%= @user.username %>'s Activity</h5>

<ul class='nav nav-tabs'>
  <li class='<%= 'active' if params[:tab].nil? %>'>
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>
  <li class='<%= 'active' if params[:tab] == 'comments' %>'>
    <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
  </li>
</ul>

<% if params[:tab].nil? %>
  <% @user.posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>
<% elsif params[:tab] == 'comments' %>
  <% @user.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment, show_post: true %>
  <% end %>
<% end %>